/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmAnggota.java
 *
 */
package Forms;
import Class.ClassDatabase;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class FrmAnggota extends javax.swing.JInternalFrame {

    /** Creates new form FrmAnggota */
    public FrmAnggota() {
        initComponents();
        datatabel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtTgl = new com.toedter.calendar.JDateChooser();
        TxtNoAnggota = new javax.swing.JTextField();
        TxtNamaAnggota = new javax.swing.JTextField();
        TxtAlamat = new javax.swing.JTextField();
        Tambah = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        tutup = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TxtSimpananPokok = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtTempatLahir = new javax.swing.JTextField();
        TxtTglLahir = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        TxtJenisKelamin = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel1 = new javax.swing.JTable();
        pencarian = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tanggal Masuk");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nomor Anggota");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Alamat");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nama Anggota");
        jLabel4.setName("jLabel4"); // NOI18N

        TxtTgl.setName("TxtTgl"); // NOI18N

        TxtNoAnggota.setName("TxtNoAnggota"); // NOI18N
        TxtNoAnggota.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtNoAnggotaCaretUpdate(evt);
            }
        });

        TxtNamaAnggota.setName("TxtNamaAnggota"); // NOI18N
        TxtNamaAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaAnggotaActionPerformed(evt);
            }
        });

        TxtAlamat.setName("TxtAlamat"); // NOI18N

        Tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/reset.png"))); // NOI18N
        Tambah.setText("Tambah");
        Tambah.setName("Tambah"); // NOI18N
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        Simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/add.png"))); // NOI18N
        Simpan.setText("Simpan");
        Simpan.setName("Simpan"); // NOI18N
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/edit.png"))); // NOI18N
        Edit.setText("Edit");
        Edit.setName("Edit"); // NOI18N
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/hapus.png"))); // NOI18N
        Hapus.setText("Hapus");
        Hapus.setName("Hapus"); // NOI18N
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        tutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/sign-out-option.png"))); // NOI18N
        tutup.setText("Tutup");
        tutup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tutup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tutup.setName("tutup"); // NOI18N
        tutup.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tutup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Simp. Pokok");
        jLabel6.setName("jLabel6"); // NOI18N

        TxtSimpananPokok.setName("TxtSimpananPokok"); // NOI18N
        TxtSimpananPokok.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtSimpananPokokCaretUpdate(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Tempat/ Tgl Lahir");
        jLabel7.setName("jLabel7"); // NOI18N

        TxtTempatLahir.setName("TxtTempatLahir"); // NOI18N
        TxtTempatLahir.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtTempatLahirCaretUpdate(evt);
            }
        });

        TxtTglLahir.setName("TxtTglLahir"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Jenis Kelamin");
        jLabel8.setName("jLabel8"); // NOI18N

        TxtJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-Laki", "Perempuan" }));
        TxtJenisKelamin.setName("TxtJenisKelamin"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        Tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel1.setName("Tabel1"); // NOI18N
        Tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tabel1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel1);

        pencarian.setName("pencarian"); // NOI18N
        pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/search.png"))); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("INPUT DATA ANGGOTA");
        jLabel5.setName("jLabel5"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Tambah)
                                            .addComponent(TxtSimpananPokok, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Simpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TxtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TxtJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tutup))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Hapus)
                                .addGap(0, 175, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tutup)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pencarian)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtSimpananPokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   //untuk tampilkan tulisan title tabel
    public void datatabel(){
        DefaultTableModel tab=new DefaultTableModel();
        tab.addColumn("No Anggota");
        tab.addColumn("Nama Anggota");
        tab.addColumn("Alamat");
        tab.addColumn("Tanggal Masuk");
        tab.addColumn("Simpanan Pokok");
        tab.addColumn("Tempat Lahir");
        tab.addColumn("Tanggal Lahir");
        tab.addColumn("Jenis Kelamin");
        
            Tabel1.setModel(tab);
            try{
                Statement statement=(Statement) ClassDatabase.getkoneksi().createStatement();
                ResultSet rs=statement.executeQuery("select * from anggota order by NoAnggota");
                while(rs.next())
                {
                    tab.addRow(new Object[]{
                        rs.getString("NoAnggota"),
                        rs.getString("Nama"),
                        rs.getString("Alamat"),
                        rs.getString("Tgl_Masuk"),
                        rs.getString("SimpananPokok"),
                        rs.getString("TempatLahir"),
                        rs.getString("TglLahir"),
                        rs.getString("Jeniskelamin")});
                        
                }
                Tabel1.setModel(tab);
                } catch (SQLException e){
            }
    }
private void TxtNamaAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaAnggotaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TxtNamaAnggotaActionPerformed

private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
// TODO add your handling code here:
   //untuk menambah data
    try {        
        
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select NoAnggota from Anggota order by NoAnggota desc ";
            ResultSet r=s.executeQuery(sql);
            
            if(r.next())
            {
                StringBuffer strBuf = new StringBuffer();
                strBuf.append(r.getString("NoAnggota"));
                String kd=String.valueOf(strBuf.delete(0, 2));
                int no_t=Integer.parseInt(kd) +1;
                
               
                this.TxtNoAnggota.setText("AG" + String.valueOf(no_t));
            }else{
                int no_t=1;
                this.TxtNoAnggota.setText("AG" + String.valueOf(no_t));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        }        
     //untuk tobol reset
        TxtNamaAnggota.setText("");
        TxtAlamat.setText("");
        TxtTempatLahir.setText("");
        TxtTglLahir.setDate(null);
        TxtSimpananPokok.setText("");
        TxtTgl.setDate(null);
    
}//GEN-LAST:event_TambahActionPerformed

private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
// TODO add your handling code here:
    //untuk menyimpan data
    java.util.Date tgl=(java.util.Date) this.TxtTgl.getDate();
    String kode=this.TxtNoAnggota.getText();
    String nama=this.TxtNamaAnggota.getText();
    String alamat=this.TxtAlamat.getText();
    String sp=this.TxtSimpananPokok.getText();
    String tl=this.TxtTempatLahir.getText();
    java.util.Date tgll=(java.util.Date) this.TxtTglLahir.getDate();
    String jenis=(String)this.TxtJenisKelamin.getSelectedItem();
    
    try {
            Connection c=ClassDatabase.getkoneksi();
            String sql = "Insert into anggota values (?,?,?,?,?,?,?,?)";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kode);
            p.setString(2, nama);  
            p.setString(3, alamat);
            p.setDate(4, new java.sql.Date(tgl.getTime()));
            p.setString(5, sp);
            p.setString(6, tl);
            p.setDate(7, new java.sql.Date(tgll.getTime()));
            p.setString(8, jenis);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Tambah data");
        }catch(SQLException e){
            System.out.println(e);
        }finally{
            
            
        }
    datatabel();
}//GEN-LAST:event_SimpanActionPerformed

private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
// TODO add your handling code here:
    //untuk mengedit data
    java.util.Date tgl=(java.util.Date) this.TxtTgl.getDate();
    String kode=this.TxtNoAnggota.getText();
    String nama=this.TxtNamaAnggota.getText();
    String alamat=this.TxtAlamat.getText();
    String sp=this.TxtSimpananPokok.getText();
    String tl=this.TxtTempatLahir.getText();
    java.util.Date tgll=(java.util.Date) this.TxtTglLahir.getDate();
    String jenis=(String)this.TxtJenisKelamin.getSelectedItem();
    try {
            Connection c=ClassDatabase.getkoneksi();
            String sql ="UPDATE `koperasi`.`anggota` SET `Nama` = ?,`Alamat` = ?,`Tgl_Masuk`=?,`SimpananPokok`=?,`TempatLahir`=?,`TglLahir`=?,`JenisKelamin`=? where NoAnggota=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(4, sp);
            p.setString(8, kode);
            p.setString(1, nama);  
            p.setString(2, alamat);
            p.setDate(3, new java.sql.Date(tgl.getTime()));
            p.setString(5, tl);
            p.setDate(6, new java.sql.Date(tgll.getTime()));
            p.setString(7, jenis);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Update data");
        }catch(SQLException e){
            System.out.println(e);
        }finally{
            
            
        }
    datatabel();
}//GEN-LAST:event_EditActionPerformed

private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
// TODO add your handling code here:
    //untuk menghapus data
     java.util.Date tgl=(java.util.Date) this.TxtTgl.getDate();
    String kode=this.TxtNoAnggota.getText();
    
    try {
            Connection c=ClassDatabase.getkoneksi();
            String sql = "Delete from anggota Where NoAnggota=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kode);          
           
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Hapus data");
        }catch(SQLException e){
            System.out.println(e);
        }finally{
            
            
        }
    datatabel();
}//GEN-LAST:event_HapusActionPerformed

private void tutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_tutupActionPerformed

private void TxtNoAnggotaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtNoAnggotaCaretUpdate
// TODO add your handling code here:
    try {            
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select * from anggota where NoAnggota='" + this.TxtNoAnggota.getText() + "'";
            ResultSet r=s.executeQuery(sql);
            
           while (r.next()){
                this.TxtNamaAnggota.setText(r.getString(2));
                this.TxtAlamat.setText(r.getString("Alamat"));
                this.TxtTgl.setDate(r.getDate("Tgl_Masuk"));
                this.TxtTempatLahir.setText(r.getString("TempatLahir"));
                this.TxtTglLahir.setDate(r.getDate("TglLahir"));
                this.TxtJenisKelamin.setSelectedItem(r.getString("JenisKelamin"));
                this.TxtSimpananPokok.setText(r.getString("SimpananPokok"));
                
            }
            r.close();
            s.close();
            
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan" + e);
        }
}//GEN-LAST:event_TxtNoAnggotaCaretUpdate

private void TxtSimpananPokokCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtSimpananPokokCaretUpdate
// TODO add your handling code here:
}//GEN-LAST:event_TxtSimpananPokokCaretUpdate

private void TxtTempatLahirCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtTempatLahirCaretUpdate
// TODO add your handling code here:
}//GEN-LAST:event_TxtTempatLahirCaretUpdate

    private void Tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel1MouseClicked
        // TODO add your handling code here:
        // untuk tabel
        TxtNoAnggota.setText(Tabel1.getValueAt(Tabel1.getSelectedRow(), 0).toString());
        TxtNamaAnggota.setText(Tabel1.getValueAt(Tabel1.getSelectedRow(), 1).toString());
        TxtAlamat.setText(Tabel1.getValueAt(Tabel1.getSelectedRow(), 2).toString());
        TxtSimpananPokok.setText(Tabel1.getValueAt(Tabel1.getSelectedRow(), 4).toString());
        TxtTempatLahir.setText(Tabel1.getValueAt(Tabel1.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_Tabel1MouseClicked

    private void Tabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel1MousePressed
        // TODO add your handling code here:
         //untuk menampilkan date jika di klik isi tabel
        if(evt.getClickCount()==1){
            TxtTgl.setDate(getTanggalFromTable(Tabel1, 3));
            TxtTglLahir.setDate(getTanggalFromTable(Tabel1, 6));      
        }
    }//GEN-LAST:event_Tabel1MousePressed

    private void pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianActionPerformed
        // TODO add your handling code here:
        // untuk pencarian
        DefaultTableModel tab= new DefaultTableModel();
        tab.addColumn("No Anggota");
        tab.addColumn("Nama Anggota");
        tab.addColumn("Alamat");
        tab.addColumn("Tanggal Masuk");
        tab.addColumn("Simpanan Pokok");
        tab.addColumn("Tempat Lahir");
        tab.addColumn("Tanggal Lahir");
        tab.addColumn("Jenis Kelamin");

try{
Statement statement =(Statement)ClassDatabase.getkoneksi().createStatement();
ResultSet rs = statement.executeQuery("select * from anggota where NoAnggota like '%"+pencarian.getText()+"%'" 
+ "or Nama like '%" + pencarian.getText()+"%'");
   while (rs.next()) {
     tab.addRow(new Object[]{
     rs.getString(1),
     rs.getString(2),
     rs.getString(3),
     rs.getString(4),
     rs.getString(5),
     rs.getString(6),
     rs.getString(7),
     rs.getString(8)
});
}
Tabel1.setModel(tab);

}catch (Exception e){
}
    }//GEN-LAST:event_pencarianActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Simpan;
    private javax.swing.JTable Tabel1;
    private javax.swing.JButton Tambah;
    private javax.swing.JTextField TxtAlamat;
    private javax.swing.JComboBox TxtJenisKelamin;
    private javax.swing.JTextField TxtNamaAnggota;
    private javax.swing.JTextField TxtNoAnggota;
    private javax.swing.JTextField TxtSimpananPokok;
    private javax.swing.JTextField TxtTempatLahir;
    private com.toedter.calendar.JDateChooser TxtTgl;
    private com.toedter.calendar.JDateChooser TxtTglLahir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pencarian;
    private javax.swing.JButton tutup;
    // End of variables declaration//GEN-END:variables

    private Date getTanggalFromTable(JTable Tabel1, int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
