/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmAngsuran.java
 *
 * Created on 25 Jun 12, 23:12:00
 */
package Forms;
import Class.ClassDatabase;
import Class.angsuran;
import Class.pinjaman;
import com.mysql.jdbc.PreparedStatement;
import com.sun.org.apache.xalan.internal.xsltc.runtime.BasisLibrary;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class FrmAngsuran extends javax.swing.JInternalFrame {
String sql1;
    /** Creates new form FrmAngsuran */
    public FrmAngsuran() {
        initComponents();
        loadcombodata();
        datatabel();
    }
private void loadcombodata(){
    try {        
//        TxtNoAnggota.removeAllItems();
        
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select NoAnggota from anggota group by NoAnggota";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
//                TxtNoAnggota.addItem(r.getString("NoAnggota"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        }   
    
    try {        
        TxtKodePinjam.removeAllItems();
        
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select NoPinjam from pinjaman where sisa > 0 group by NoPinjam";
            ResultSet r=s.executeQuery(sql);
           
            while (r.next()) {
                TxtKodePinjam.addItem(r.getString("NoPinjam"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        }
}
//untuk tampilkan tulisan title tabel
    public void datatabel(){
        DefaultTableModel tab=new DefaultTableModel();
        tab.addColumn("No Bukti");
        tab.addColumn("Tanggal Bukti");
        tab.addColumn("No Pinjam");
        tab.addColumn("Jasa");
        tab.addColumn("Angsuran");
        tab.addColumn("Total Angsuran");
        tab.addColumn("Sisa");
        tab.addColumn("Ke");
       
        
            Tabel4.setModel(tab);
            try{
                Statement statement=(Statement) ClassDatabase.getkoneksi().createStatement();
                ResultSet rs=statement.executeQuery("select * from angsuran order by ke desc,NoBukti Desc");
                while(rs.next())
                {
                    tab.addRow(new Object[]{
                        rs.getString("NoBukti"),
                        rs.getString("TglBukti"),
                        rs.getString("NoPinjam"),
                        rs.getString("Jasa"),
                        rs.getString("Angsuran"),
                        rs.getString("Total_Angsuran"),
                        rs.getString("Sisa"),
                        rs.getString("Ke")});
                        
                }
                Tabel4.setModel(tab);
                } catch (SQLException e){
            }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNamaAnggota = new javax.swing.JTextField();
        TxtLamaPinjam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TxtTotalPinjam = new javax.swing.JTextField();
        TxtTotalBayar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TxtSisa = new javax.swing.JTextField();
        Tambah = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        TxtKodePinjam = new javax.swing.JComboBox();
        TxtTgl = new com.toedter.calendar.JDateChooser();
        TxtNoBukti = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TxtAngsuran = new javax.swing.JTextField();
        Hapus = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        pencarian = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TxtJasa = new javax.swing.JTextField();
        TxtTanggalAngsur = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel4 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        coba = new javax.swing.JTextField();
        txtNo_anggota = new javax.swing.JTextField();

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Nomor Anggota");
        jLabel11.setName("jLabel11"); // NOI18N

        jTextField5.setName("jTextField5"); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setName("jTextField6"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nama Anggota");
        jLabel10.setName("jLabel10"); // NOI18N

        setBackground(new java.awt.Color(0, 51, 102));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Kode Pinjaman");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Tanggal Pinjam");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nomor Anggota");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nama Anggota");
        jLabel4.setName("jLabel4"); // NOI18N

        TxtNamaAnggota.setName("TxtNamaAnggota"); // NOI18N
        TxtNamaAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaAnggotaActionPerformed(evt);
            }
        });

        TxtLamaPinjam.setName("TxtLamaPinjam"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Lama Pinjaman");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("No Bukti");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Tanggal Angsur");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Total Pinjaman");
        jLabel12.setName("jLabel12"); // NOI18N

        TxtTotalPinjam.setName("TxtTotalPinjam"); // NOI18N

        TxtTotalBayar.setName("TxtTotalBayar"); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Total Bayar");
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Sisa");
        jLabel14.setName("jLabel14"); // NOI18N

        TxtSisa.setName("TxtSisa"); // NOI18N

        Tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/reset.png"))); // NOI18N
        Tambah.setText("Tambah");
        Tambah.setName("Tambah"); // NOI18N
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        Simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/add.png"))); // NOI18N
        Simpan.setText("Simpan");
        Simpan.setName("Simpan"); // NOI18N
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/sign-out-option.png"))); // NOI18N
        jButton5.setText("Tutup");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setName("jButton5"); // NOI18N
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        TxtKodePinjam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TxtKodePinjam.setName("TxtKodePinjam"); // NOI18N
        TxtKodePinjam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TxtKodePinjamItemStateChanged(evt);
            }
        });
        TxtKodePinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKodePinjamActionPerformed(evt);
            }
        });

        TxtTgl.setName("TxtTgl"); // NOI18N

        TxtNoBukti.setName("TxtNoBukti"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Angsuran Ke");
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Angsuran");
        jLabel16.setName("jLabel16"); // NOI18N

        TxtAngsuran.setName("TxtAngsuran"); // NOI18N

        Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/hapus.png"))); // NOI18N
        Hapus.setText("Hapus");
        Hapus.setName("Hapus"); // NOI18N
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/search.png"))); // NOI18N
        jButton6.setName("jButton6"); // NOI18N

        pencarian.setName("pencarian"); // NOI18N
        pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("INPUT DATA ANGSURAN");
        jLabel18.setName("jLabel18"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel18)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Jasa");
        jLabel17.setName("jLabel17"); // NOI18N

        TxtJasa.setName("TxtJasa"); // NOI18N

        TxtTanggalAngsur.setName("TxtTanggalAngsur"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        Tabel4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel4.setName("Tabel4"); // NOI18N
        Tabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tabel4MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(Tabel4);

        jTextField1.setName("jTextField1"); // NOI18N

        jTextField2.setName("jTextField2"); // NOI18N

        jTextField3.setName("jTextField3"); // NOI18N

        jTextField4.setName("jTextField4"); // NOI18N

        coba.setName("coba"); // NOI18N

        txtNo_anggota.setName("txtNo_anggota"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(TxtLamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtTotalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(TxtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(TxtKodePinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNo_anggota)
                            .addComponent(TxtTgl, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)))
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(TxtNoBukti, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel17)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel15)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtJasa, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(TxtTotalBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(TxtSisa, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(TxtTanggalAngsur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(coba))))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Tambah)
                        .addGap(18, 18, 18)
                        .addComponent(Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Hapus)
                        .addGap(225, 225, 225))))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel6))
                            .addComponent(TxtKodePinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtTgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNo_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtLamaPinjam)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtNoBukti)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtTanggalAngsur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtJasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtSisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTotalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void TxtNamaAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaAnggotaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TxtNamaAnggotaActionPerformed

private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField5ActionPerformed

private void TxtKodePinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKodePinjamActionPerformed
// TODO add your handling code here:
    //untuk menampilkan isi yang ada didalam form pinjaman
    pinjaman pinjam = new pinjaman();
    int i=TxtKodePinjam.getSelectedIndex();
        if (i == -1)
        {
            return;
        }
        
        tampilData(pinjam.getData(TxtKodePinjam.getSelectedItem().toString()));
        
//        System.out.println(TxtKodePinjam.getSelectedItem().toString());
//        "Select * from pinjaman WHERE NoPinjam=?"
//        tes2((String) TxtKodePinjam.getSelectedItem());
}//GEN-LAST:event_TxtKodePinjamActionPerformed

private void tampilData(ResultSet data){
    pinjaman pinjam = new pinjaman();
    try {
        txtNo_anggota.setText(data.getString("NoAnggota"));
        TxtTgl.setDate(data.getDate("TglPinjam"));
        TxtNamaAnggota.setText(data.getString("Nama"));
        TxtLamaPinjam.setText(data.getString("lama"));
        TxtAngsuran.setText(String.valueOf(data.getInt("jumlah") / data.getInt("lama")));
        TxtTotalPinjam.setText(data.getString("jumlah"));
        
//        TxtJasa.setText(String.valueOf(pinjam.sisaPinjaman(data.getString("NoPinjam"))));
        coba.setText(String.valueOf(pinjam.AngsurKe(data.getString("NoPinjam"))));
        TxtSisa.setText(String.valueOf(pinjam.sisaPinjaman(data.getString("NoPinjam"))));
        TxtJasa.setText(String.valueOf(pinjam.jasa(pinjam.sisaPinjaman(data.getString("NoPinjam")))));
        TxtTotalBayar.setText(String.valueOf((data.getInt("jumlah") / data.getInt("lama")) + pinjam.jasa(pinjam.sisaPinjaman("PJ7"))));
    } catch (Exception e) {
    }
}



private void tes2(String bla){
    try {
       
            String kd=bla;
            Connection c = ClassDatabase.getkoneksi();
            Statement s = c.createStatement();           
//            String sql = "Select * from pinjaman WHERE NoPinjam=?" ;
            String sql = "Select pinjaman.NoPinjam, pinjaman.NoAnggota, pinjaman.Lama, pinjaman.Bunga, pinjaman.Jumlah, pinjaman.Jasa, pinjaman.Angsuran, pinjaman.Sisa, pinjaman.TglPinjam, angsuran.NoBukti, angsuran.TglBukti, angsuran.NoPinjam, angsuran.Jasa, angsuran.Angsuran, angsuran.Total_Angsuran, angsuran.Sisa, angsuran.Ke from pinjaman LEFT JOIN angsuran ON pinjaman.NoPinjam=angsuran.NoPinjam WHERE pinjaman.NoPinjam=? ORDER BY `Ke` DESC ";
//            String sql = "Select * from pinjaman LEFT JOIN angsuran ON pinjaman.NoPinjam=angsuran.NoPinjam WHERE pinjaman.NoPinjam=? ORDER BY `NoAnggota`";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kd);
            ResultSet result=p.executeQuery();
            result.next();
//            double we = Double.parseDouble(result.getString("Sisa"));
//            double we1 = (we * 0.06);
//            double wa =  Double.parseDouble(result.getString("Sisa")) - Double.parseDouble(result.getString("Angsuran"));
//            double wa1 = we1 + Double.parseDouble(result.getString("Angsuran"));
//            int qwe = 1;
//            Integer jasa =  Integer.parseInt(result.getString("Bunga")) / 100 * Integer.parseInt(result.getString("Sisa")) ;
//           Double jasa =  4/4;
            Integer tes = Integer.parseInt(result.getString("Sisa"));
            String percobaan = "default";
            if (tes == 0) {
                    percobaan = "tes ini";
        }else{
                percobaan = "ade isi nye";
            }
            Double jasa=Double.parseDouble(result.getString("Bunga"))/100*Double.parseDouble(result.getString("Sisa"));
            Double totalangsuran=Double.parseDouble(result.getString("Jasa"))+Double.parseDouble(result.getString("Angsuran"));
            Double sisa=Double.parseDouble(result.getString("Jumlah"))-Double.parseDouble(result.getString("Angsuran"));            
            String KE = result.getString("Ke");
           int qwe = 1 + BasisLibrary.stringToInt(KE);
           this.TxtTgl.setDate(result.getDate("TglPinjam"));
//           this.TxtNoAnggota.setSelectedItem(result.getString("NoAnggota"));
           this.TxtLamaPinjam.setText(result.getString("Lama"));
           this.TxtTotalPinjam.setText(result.getString("Jumlah"));
           this.TxtAngsuran.setText(result.getString("pinjaman.Angsuran"));
//           this.TxtJasa.setText(Double.toString(we1));
           this.TxtJasa.setText(String.valueOf(jasa));
//           this.TxtJasa.setText(percobaan);

//           this.TxtTotalBayar.setText(Double.toString(wa1));
           this.TxtTotalBayar.setText(String.valueOf(totalangsuran));
           this.TxtSisa.setText(String.valueOf(sisa));
//           this.coba.setText(asdf);
//            this.TxtAngsuranKe.removeAllItems();
            if (qwe == 0) {
                qwe = 1;
            }else if(qwe == 2){
                qwe=2;
            }
            this.coba.setText(Integer.toString(qwe));
//            this.coba.setText(apk);

       
//           int pk=Integer.parseInt(result.getString("Lama"));
//           
//                   for(int i2=1; i2<=pk; i2++)
//                    {
//                        this.TxtAngsuranKe.addItem(String.valueOf(i2));
//                    }
                   
                          

            }catch(SQLException e){
            System.out.println(e);        
         }
    
}

private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
// TODO add your handling code here:
    try {        
        
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="select right(nobukti,length(nobukti)-2) as NoBukti from angsuran order by convert(right(nobukti,length(nobukti)-2), decimal) DESC limit 1";
            ResultSet r=s.executeQuery(sql);
            
            if(r.next())
            {
//                StringBuffer strBuf = new StringBuffer();
//                strBuf.append(r.getString("NoBukti"));
//                String kd=String.valueOf(strBuf.delete(0, 2));
                int no_t=r.getInt("NoBukti") +1;
                
               
                this.TxtNoBukti.setText("BA" + String.valueOf(no_t));
//                this.coba.setText(String.valueOf(no_t));
            }else{
                int no_t=1;
                this.TxtNoBukti.setText("BA" + String.valueOf(no_t));
//                this.coba.setText(String.valueOf(no_t));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        }     
    
}//GEN-LAST:event_TambahActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jButton5ActionPerformed

private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
// TODO add your handling code here:
   
          //untuk tombol tambah
//        String NoBukti=TxtNoBukti.getText();
////        String Angsuranke=(String) TxtAngsuranKe.getSelectedItem();
//        String Angsuranke=(String) coba.getText();
//        String TotalAngsuran=TxtTotalBayar.getText();
//         java.util.Date TglAngsuran=(java.util.Date) this.TxtTanggalAngsur.getDate();
//        String NoPinjam=(String) TxtKodePinjam.getSelectedItem();
////        Integer Jasa=Integer.parseInt(TxtJasa);
//        String Angsuran=(String) TxtAngsuran.getText();
//        String Sisa=(String) TxtSisa.getText();
      
       
//          try {
//            Connection c=ClassDatabase.getkoneksi();
//            String sql = "Insert into angsuran values (?,?,?,?,?,?,?,?)";
//            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
//            p.setString(1, NoBukti);
//            p.setDate(2, new java.sql.Date(TglAngsuran.getTime()));
//            p.setString(3, NoPinjam);  
////            p.setString(4, Jasa);
//             p.setString(5, Angsuran);
//             p.setString(6, TotalAngsuran);
//             p.setString(7, Sisa);  
//            p.setString(8, Angsuranke);
//          
//           
//            p.executeUpdate();
//            p.close();
////            FrmAngsuran a = new FrmAngsuran();
////            a.setVisible(true);
//            tes2((String) TxtKodePinjam.getSelectedItem());
//            JOptionPane.showMessageDialog(this, "Sukses Tambah data");
//        }catch(SQLException e){
//            System.out.println(e);
//        }finally{
//            
//            
//        }
        angsuran angsur = new angsuran();
        pinjaman pinjam = new pinjaman();
        angsur.noBukti = TxtNoBukti.getText();
        angsur.tglBukti = (java.util.Date) this.TxtTanggalAngsur.getDate();
        angsur.noPinjam = (String) TxtKodePinjam.getSelectedItem();
        angsur.jasa = Integer.parseInt(TxtJasa.getText());
        angsur.angsuran = Integer.parseInt(TxtAngsuran.getText());
        angsur.totalAngsuran = Integer.parseInt(TxtTotalBayar.getText());
        angsur.sisa = Integer.parseInt(TxtSisa.getText()) - angsur.angsuran;
        angsur.ke = Integer.parseInt(coba.getText());
        try {
            angsur.tambah();
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage().toString());
        }
    datatabel();
    tampilData(pinjam.getData(TxtKodePinjam.getSelectedItem().toString()));
//    FrmAngsuran s=new FrmAngsuran();
//    this.desktopPane.add(s);
//    s.show();
}//GEN-LAST:event_SimpanActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        
    String kodeB=this.TxtNoBukti.getText(); 
    try {
            Connection c=ClassDatabase.getkoneksi();
            String sql = "Delete from angsuran Where NoBukti=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kodeB);
           
           
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Hapus data");
        }catch(SQLException e){
            System.out.println(e);
        }finally{
            
              
    }
      datatabel(); 
    }//GEN-LAST:event_HapusActionPerformed

    private void Tabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel4MouseClicked
        // TODO add your handling code here
        TxtNoBukti.setText(Tabel4.getValueAt(Tabel4.getSelectedRow(), 0).toString());
        //TxtWajib.setText(Tabel2.getValueAt(Tabel2.getSelectedRow(), 3).toString());
//         TxtTanggalAngsur.setDate(getTanggalFromTable(Tabel4, 1));
    }//GEN-LAST:event_Tabel4MouseClicked

    private void Tabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel4MousePressed
        // TODO add your handling code here:
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
         if(evt.getClickCount()==1){
//            TxtTanggalAngsur.setDate(getTanggalFromTable(Tabel4, 1));
             try {
                 Date date = formatter.parse(Tabel4.getValueAt(Tabel4.getSelectedRow(), 1).toString());
                 TxtTanggalAngsur.setDate(date);
             } catch (Exception e) {
             }
//            Tabel4.getValueAt(Tabel4.getSelectedRow(), 0).toString()
        }
    }//GEN-LAST:event_Tabel4MousePressed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
    }//GEN-LAST:event_formInternalFrameActivated

    private void pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianActionPerformed
        // TODO add your handling code here:
          // untuk pencarian
        DefaultTableModel tab= new DefaultTableModel();
        tab.addColumn("No Bukti");
        tab.addColumn("Tanggal Bukti");
        tab.addColumn("No Pinjam");
        tab.addColumn("Jasa");
        tab.addColumn("Angsuran");
        tab.addColumn("Total Angsuran");
        tab.addColumn("Sisa");
        tab.addColumn("Ke");

try{
Statement statement =(Statement)ClassDatabase.getkoneksi().createStatement();
ResultSet rs = statement.executeQuery("select * from angsuran where NoPinjam like '%"+pencarian.getText()+"%' order by convert(right(nobukti,length(nobukti)-2), decimal) DESC");
   while (rs.next()) {
     tab.addRow(new Object[]{
     rs.getString(1),
     rs.getString(2),
     rs.getString(3),
     rs.getString(4),
     rs.getString(5),
     rs.getString(6),
     rs.getString(7),
     rs.getString(8)
});
}
Tabel4.setModel(tab);

}catch (Exception e){
}
    }//GEN-LAST:event_pencarianActionPerformed

    private void TxtKodePinjamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TxtKodePinjamItemStateChanged
        // TODO add your handling code here:
//        System.out.println(TxtKodePinjam.getSelectedItem().toString());
    }//GEN-LAST:event_TxtKodePinjamItemStateChanged

private void updateangsur()
{
    String nb=this.TxtNoBukti.getText();
    java.util.Date tb=(java.util.Date) this.TxtTanggalAngsur.getDate();    
    String kp=(String) this.TxtKodePinjam.getSelectedItem();
    String ja=this.TxtAngsuran.getText();
    String ke=this.coba.getText();

//    String ke=(String) this.TxtAngsuranKe.getSelectedItem();
   // String 
   
    try {
            Connection c=ClassDatabase.getkoneksi();
            String sql = "Update pinjaman set Total_Angsuran=Total_Angsuran + ? where NoPinjam=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, ja);
           
             p.setString(2, nb);
           
            p.executeUpdate();
            p.close();
            
        }catch(SQLException e){
            System.out.println(e);
        }finally{
            
            
        } 
}

private void updatesisa()
{
    String nb=this.TxtNoBukti.getText();
    java.util.Date tb=(java.util.Date) this.TxtTanggalAngsur.getDate();    
    String kp=(String) this.TxtKodePinjam.getSelectedItem();
    String ja=this.TxtAngsuran.getText();
    String ke=this.coba.getText();

//    String ke=(String) this.TxtAngsuranKe.getSelectedItem();
   // String 
   
    try {
            Connection c=ClassDatabase.getkoneksi();
            String sql = "Update pinjaman set Sisa=Jumlah - Total_Angsuran  where NoPinjam=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
           
           
             p.setString(1, nb);
           
            p.executeUpdate();
            p.close();
            
        }catch(SQLException e){
            System.out.println(e);
        }finally{
            
            
        } 
}

private void simpan()
{
    String nb=this.TxtNoBukti.getText();
    java.util.Date tb=(java.util.Date) this.TxtTanggalAngsur.getDate();    
    String kp=(String) this.TxtKodePinjam.getSelectedItem();
    String ja=this.TxtAngsuran.getText();
    String ke=this.coba.getText();
//    String ke=(String) this.TxtAngsuranKe.getSelectedItem();
   // String 
   
    try {
            Connection c=ClassDatabase.getkoneksi();
            String sql = "Insert into angsuran values (?,?,?,?,?)";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, nb);
            p.setDate(2, new java.sql.Date(tb.getTime()));
            p.setString(3,kp);  
            p.setString(4, ja);
             p.setString(5, ke);
           
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Tambah data");
        }catch(SQLException e){
            System.out.println(e);
        }finally{
            
            
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Simpan;
    private javax.swing.JTable Tabel4;
    private javax.swing.JButton Tambah;
    private javax.swing.JTextField TxtAngsuran;
    private javax.swing.JTextField TxtJasa;
    private javax.swing.JComboBox TxtKodePinjam;
    private javax.swing.JTextField TxtLamaPinjam;
    private javax.swing.JTextField TxtNamaAnggota;
    private javax.swing.JTextField TxtNoBukti;
    private javax.swing.JTextField TxtSisa;
    private com.toedter.calendar.JDateChooser TxtTanggalAngsur;
    private com.toedter.calendar.JDateChooser TxtTgl;
    private javax.swing.JTextField TxtTotalBayar;
    private javax.swing.JTextField TxtTotalPinjam;
    private javax.swing.JTextField coba;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField pencarian;
    private javax.swing.JTextField txtNo_anggota;
    // End of variables declaration//GEN-END:variables

    private Date getTanggalFromTable(JTable Tabel4, int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
