/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmPinjaman.java
 *
 * Created on 25 Jun 12, 23:05:48
 */
package Forms;
import Class.ClassDatabase;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class FrmPinjaman extends javax.swing.JInternalFrame {

    /** Creates new form FrmPinjaman */
    public FrmPinjaman() {
        initComponents();
        loadcombodata();
        datatabel();
        tanggal();
    }
private void loadcombodata(){
    try {        
        TxtNoAnggota.removeAllItems();
        
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select NoAnggota from anggota group by NoAnggota";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                TxtNoAnggota.addItem(r.getString("NoAnggota"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        }   
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
public void tanggal()
{
    Date ys = new Date();
    SimpleDateFormat s= new SimpleDateFormat("yyyy-MM-dd");
    TxtTanggal.setText(s.format(ys));
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        Simpan = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Tambah = new javax.swing.JButton();
        TxtBunga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtKodePinjam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtNoAnggota = new javax.swing.JComboBox();
        Tutup = new javax.swing.JButton();
        TxtLamaPinjam = new javax.swing.JTextField();
        Hapus = new javax.swing.JButton();
        TxtNamaAnggota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtJumlahPinjaman = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtAngsuran = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel3 = new javax.swing.JTable();
        pencarian = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxtJasa = new javax.swing.JTextField();
        TxtTanggal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 102));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nama Anggota");
        jLabel4.setName("jLabel4"); // NOI18N

        Simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/add.png"))); // NOI18N
        Simpan.setText("Simpan");
        Simpan.setName("Simpan"); // NOI18N
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/edit.png"))); // NOI18N
        Edit.setText("Edit");
        Edit.setName("Edit"); // NOI18N
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/reset.png"))); // NOI18N
        Tambah.setText("Tambah");
        Tambah.setName("Tambah"); // NOI18N
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        TxtBunga.setName("TxtBunga"); // NOI18N
        TxtBunga.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtBungaCaretUpdate(evt);
            }
        });
        TxtBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBungaActionPerformed(evt);
            }
        });
        TxtBunga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtBungaKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Bunga (%)");
        jLabel7.setName("jLabel7"); // NOI18N

        TxtKodePinjam.setName("TxtKodePinjam"); // NOI18N
        TxtKodePinjam.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtKodePinjamCaretUpdate(evt);
            }
        });
        TxtKodePinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKodePinjamActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Kode Pinjaman");
        jLabel6.setName("jLabel6"); // NOI18N

        TxtNoAnggota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TxtNoAnggota.setName("TxtNoAnggota"); // NOI18N
        TxtNoAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNoAnggotaActionPerformed(evt);
            }
        });

        Tutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/sign-out-option.png"))); // NOI18N
        Tutup.setText("Tutup");
        Tutup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tutup.setName("Tutup"); // NOI18N
        Tutup.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Tutup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutupActionPerformed(evt);
            }
        });

        TxtLamaPinjam.setName("TxtLamaPinjam"); // NOI18N
        TxtLamaPinjam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtLamaPinjamKeyPressed(evt);
            }
        });

        Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/hapus.png"))); // NOI18N
        Hapus.setText("Hapus");
        Hapus.setName("Hapus"); // NOI18N
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        TxtNamaAnggota.setName("TxtNamaAnggota"); // NOI18N
        TxtNamaAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaAnggotaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Lama Pinjaman");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nomor Anggota");
        jLabel2.setName("jLabel2"); // NOI18N

        TxtJumlahPinjaman.setName("TxtJumlahPinjaman"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Jumlah Pinjaman");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Angsuran");
        jLabel10.setName("jLabel10"); // NOI18N

        TxtAngsuran.setName("TxtAngsuran"); // NOI18N
        TxtAngsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAngsuranActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("bulan");
        jLabel11.setName("jLabel11"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        Tabel3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel3.setName("Tabel3"); // NOI18N
        Tabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tabel3MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel3);

        pencarian.setName("pencarian"); // NOI18N
        pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Jasa");
        jLabel12.setName("jLabel12"); // NOI18N

        TxtJasa.setName("TxtJasa"); // NOI18N
        TxtJasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtJasaActionPerformed(evt);
            }
        });

        TxtTanggal.setName("TxtTanggal"); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/search.png"))); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("INPUT DATA PINJAMAN");
        jLabel18.setName("jLabel18"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel18)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tutup, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(TxtJumlahPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addComponent(TxtKodePinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TxtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(54, 54, 54)
                        .addComponent(TxtBunga, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtJasa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtLamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)))))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Simpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hapus)
                .addGap(203, 203, 203))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tutup, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pencarian)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TxtBunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtLamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtJasa)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TxtAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TxtKodePinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TxtJumlahPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 //untuk tampilkan tulisan title tabel
    public void datatabel(){
        DefaultTableModel tab=new DefaultTableModel();
        tab.addColumn("Kode Pinjaman");
        tab.addColumn("Tanggal Pinjaman");
        tab.addColumn("No Anggota");
        tab.addColumn("Lama");
        tab.addColumn("Bunga");
        tab.addColumn("Jumlah");
        tab.addColumn("Jasa");
        tab.addColumn("Angsuran");
//        tab.addColumn("Total Angsuran");
        tab.addColumn("Sisa");
        
            Tabel3.setModel(tab);
            try{
                Statement statement=(Statement) ClassDatabase.getkoneksi().createStatement();
                ResultSet rs=statement.executeQuery("select distinct(Date_format(TglPinjam,'%d-%m-%Y')) as tgl,`NoPinjam`,`NoAnggota`,`Lama`,`Bunga`,`Jumlah`,`Jasa`,`Angsuran`,`Sisa` from pinjaman order by NoPinjam asc ");
                
                while(rs.next())
                {
                    tab.addRow(new Object[]{
                        rs.getString("NoPinjam"),
                        rs.getString("tgl"),
                        rs.getString("NoAnggota"),
                        rs.getString("Lama"),
                        rs.getString("Bunga"),
                        rs.getString("Jumlah"),
                        rs.getString("Jasa"),
                        rs.getString("Angsuran"),
//                        rs.getString("Total_Angsuran"),
                        rs.getString("Sisa")});
                        
                }
                Tabel3.setModel(tab);
                } catch (SQLException e){
            }
    }
private void TxtKodePinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKodePinjamActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TxtKodePinjamActionPerformed

private void TxtNamaAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaAnggotaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TxtNamaAnggotaActionPerformed

private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
// TODO add your handling code here:
    try {        
        
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select NoPinjam from Pinjaman order by NoPinjam desc";
            ResultSet r=s.executeQuery(sql);
            
            if(r.next())
            {
                StringBuffer strBuf = new StringBuffer();
                strBuf.append(r.getString("NoPinjam"));
                String kd=String.valueOf(strBuf.delete(0, 2));
                int no_t=Integer.parseInt(kd) +1;
                
               
                this.TxtKodePinjam.setText("PJ" + String.valueOf(no_t));
            }else{
                int no_t=1;
                this.TxtKodePinjam.setText("PJ" + String.valueOf(no_t));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        }    
    //untuk tobol reset
        TxtJumlahPinjaman.setText("");
        TxtLamaPinjam.setText("");
        TxtAngsuran.setText("");
        TxtJasa.setText("");
        TxtBunga.setText("");
        
       
}//GEN-LAST:event_TambahActionPerformed

private void TxtNoAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNoAnggotaActionPerformed
// TODO add your handling code here:
    int i=TxtNoAnggota.getSelectedIndex();
        if (i==-1)
        {
            return;
        }
         try {
             String kd=(String) TxtNoAnggota.getSelectedItem();
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql = "Select * from anggota WHERE NoAnggota=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kd);
            ResultSet result=p.executeQuery();
            result.next();            
            
            this.TxtNamaAnggota.setText(result.getString(2));
            
            
            }catch(SQLException e){
            System.out.println(e);        
         }
}//GEN-LAST:event_TxtNoAnggotaActionPerformed

private void TxtBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBungaActionPerformed
// TODO add your handling code here:
   
   
}//GEN-LAST:event_TxtBungaActionPerformed

private void TxtBungaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtBungaCaretUpdate
// TODO add your handling code here:
   
}//GEN-LAST:event_TxtBungaCaretUpdate

private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
// TODO add your handling code here:
    String tgl = this.TxtTanggal.getText();
    String kodeP=this.TxtKodePinjam.getText();
    String kodeA=(String) this.TxtNoAnggota.getSelectedItem();
    String jp=this.TxtJumlahPinjaman.getText();
    String lama=this.TxtLamaPinjam.getText();
    String bunga=this.TxtBunga.getText();
    String jasa=this.TxtJasa.getText();
    String angs=this.TxtAngsuran.getText();
    //untuk datatabel pinjaman khususnya total angsuran
    Double jasa1=Double.parseDouble(this.TxtJasa.getText());
   Double angsuran1=Double.parseDouble(this.TxtAngsuran.getText());
//   Double totalangsuran=jasa1+angsuran1;
   //untuk datatabel pinjaman khususnya sisa pinjaman
   
    Double jp1=Double.parseDouble(this.TxtJumlahPinjaman.getText());
   Double angsuran2=Double.parseDouble(this.TxtAngsuran.getText());
   Double sisapinjaman=jp1;
  
   
  
    
    try {
            Connection c=ClassDatabase.getkoneksi();
            String sql = "Insert into pinjaman (NoPinjam,NoAnggota,Lama,Bunga,Jumlah,Jasa,Angsuran,Sisa,TglPinjam) values (?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kodeP);
            p.setString(2, kodeA);  
            p.setString(3, lama);
             p.setString(4, bunga);
             p.setString(5, jp);
             p.setString(6, jasa);             
             p.setString(7, angs);
//            p.setDouble(8, totalangsuran);
           p.setDouble(9, sisapinjaman);
           p.setString(10, tgl);
           
           
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Tambah data");
        }catch(SQLException e){
            System.out.println(e);
        }finally{
            
            
        }
    datatabel();
               
}//GEN-LAST:event_SimpanActionPerformed


private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
// TODO add your handling code here:
    String tgl = this.TxtTanggal.getText();
    String kodeP=this.TxtKodePinjam.getText();
    String kodeA=(String) this.TxtNoAnggota.getSelectedItem();
    String jp=this.TxtJumlahPinjaman.getText();
    String lama=this.TxtLamaPinjam.getText();
    String bunga=this.TxtBunga.getText();
    String jasa=this.TxtJasa.getText();
    String angs=this.TxtAngsuran.getText();
   //untuk datatabel pinjaman khususnya total angsuran
    Double jasa1=Double.parseDouble(this.TxtJasa.getText());
   Double angsuran1=Double.parseDouble(this.TxtAngsuran.getText());
   Double totalangsuran=jasa1+angsuran1;
   //untuk datatabel pinjaman khususnya sisa pinjaman
   
    Double jp1=Double.parseDouble(this.TxtJumlahPinjaman.getText());
   Double angsuran2=Double.parseDouble(this.TxtAngsuran.getText());
   Double sisapinjaman=jp1-angsuran2;
   
    try {
            Connection c=ClassDatabase.getkoneksi();
            String sql = "Update `koperasi`.`pinjaman` SET `TglPinjam`=?,`NoAnggota`=?,`Lama`=?,`Bunga`=?,`Jumlah`=?,`Jasa`=?,`Angsuran`=?,`Total_Angsuran`=?,`Sisa`=? Where NoPinjam=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, tgl);
            p.setString(2, kodeA);
            p.setString(3, lama);
             p.setString(4, bunga);
             p.setString(5, jp);
             p.setString(6, jasa);
             p.setString(7, angs);
             p.setDouble(8, totalangsuran);
           p.setDouble(9, sisapinjaman);
             p.setString(10, kodeP);
              
           
           
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Update data");
        }catch(SQLException e){
            System.out.println(e);
        }finally{
            
            
        }
    datatabel();               
}//GEN-LAST:event_EditActionPerformed

private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
// TODO add your handling code here:
    String kodeP=this.TxtKodePinjam.getText();
   
    try {
            Connection c=ClassDatabase.getkoneksi();
            String sql = "Delete from pinjaman Where NoPinjam=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kodeP);
           
           
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Hapus data");
        }catch(SQLException e){
            System.out.println(e);
        }finally{
            
           datatabel();    
        }
            
}//GEN-LAST:event_HapusActionPerformed

private void TxtKodePinjamCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtKodePinjamCaretUpdate
// TODO add your handling code here:
    try {            
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select * from pinjaman where NoPinjam='" + this.TxtKodePinjam.getText() + "'";
            ResultSet r=s.executeQuery(sql);
            
           while (r.next()){
               
                
                this.TxtNoAnggota.setSelectedItem(r.getString("NoAnggota"));
                this.TxtLamaPinjam.setText(r.getString("Lama"));
                this.TxtBunga.setText(r.getString("Bunga"));
                this.TxtJumlahPinjaman.setText(r.getString("Jumlah"));
                this.TxtJasa.setText(r.getString("Jasa"));
                this.TxtAngsuran.setText(r.getString("Angsuran"));  
              
            }
            r.close();
            s.close();
            
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan" + e);
        }
}//GEN-LAST:event_TxtKodePinjamCaretUpdate

private void TutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutupActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_TutupActionPerformed

private void TxtBungaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBungaKeyPressed
// TODO add your handling code here:
     
    Double jp=Double.parseDouble(this.TxtJumlahPinjaman.getText());
   Double bunga=Double.parseDouble(this.TxtBunga.getText()); 
   Double totaljasa=jp* (bunga/100);
   this.TxtJasa.setText(String.valueOf(totaljasa));
   
}//GEN-LAST:event_TxtBungaKeyPressed

    private void Tabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel3MouseClicked
        // TODO add your handling code here:
         // untuk tabel
        TxtKodePinjam.setText(Tabel3.getValueAt(Tabel3.getSelectedRow(), 0).toString());
        TxtJumlahPinjaman.setText(Tabel3.getValueAt(Tabel3.getSelectedRow(), 5).toString());
        TxtLamaPinjam.setText(Tabel3.getValueAt(Tabel3.getSelectedRow(), 3).toString());  
        TxtBunga.setText(Tabel3.getValueAt(Tabel3.getSelectedRow(), 4).toString());   
         TxtJasa.setText(Tabel3.getValueAt(Tabel3.getSelectedRow(), 6).toString());
        TxtAngsuran.setText(Tabel3.getValueAt(Tabel3.getSelectedRow(), 7).toString());
        
    }//GEN-LAST:event_Tabel3MouseClicked

    private void Tabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel3MousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Tabel3MousePressed

    private void pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianActionPerformed
        // TODO add your handling code here:
         // untuk pencarian
        DefaultTableModel tab= new DefaultTableModel();
        tab.addColumn("Kode Pinjaman");
        tab.addColumn("Tanggal Pinjaman");
        tab.addColumn("No Anggota");
        tab.addColumn("Lama");
        tab.addColumn("Bunga");
        tab.addColumn("Jumlah");
        tab.addColumn("Jasa");
        tab.addColumn("Angsuran");
        tab.addColumn("Total Angsuran");
        tab.addColumn("Sisa");

try{
Statement statement =(Statement)ClassDatabase.getkoneksi().createStatement();
ResultSet rs = statement.executeQuery("select distinct(Date_format(TglPinjam,'%d-%m-%Y')) as tgl,`NoPinjam`,`NoAnggota`,`Lama`,`Bunga`,`Jumlah`,`Jasa`,`Angsuran`,`Total_Angsuran`,`Sisa` from pinjaman where NoAnggota like '%"+pencarian.getText()+"%'");
   while (rs.next()) {
     tab.addRow(new Object[]{
     rs.getString(1),
     rs.getString(2),
     rs.getString(3),
     rs.getString(4),
     rs.getString(5),
     rs.getString(6),
     rs.getString(7),
     rs.getString(8),
     rs.getString(9),
     rs.getString(10)
});
}
Tabel3.setModel(tab);

}catch (Exception e){
}
    }//GEN-LAST:event_pencarianActionPerformed

    private void TxtAngsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAngsuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAngsuranActionPerformed

    private void TxtJasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtJasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtJasaActionPerformed

    private void TxtLamaPinjamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtLamaPinjamKeyPressed
        // TODO add your handling code here:
        
    Double jp=Double.parseDouble(this.TxtJumlahPinjaman.getText());
   Double lama=Double.parseDouble(this.TxtLamaPinjam.getText());
   
   Double angsuran=jp/lama;
   this.TxtAngsuran.setText(String.valueOf(angsuran));
    }//GEN-LAST:event_TxtLamaPinjamKeyPressed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
         TxtTanggal.setVisible(false);
    }//GEN-LAST:event_formInternalFrameActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Simpan;
    private javax.swing.JTable Tabel3;
    private javax.swing.JButton Tambah;
    private javax.swing.JButton Tutup;
    private javax.swing.JTextField TxtAngsuran;
    private javax.swing.JTextField TxtBunga;
    private javax.swing.JTextField TxtJasa;
    private javax.swing.JTextField TxtJumlahPinjaman;
    private javax.swing.JTextField TxtKodePinjam;
    private javax.swing.JTextField TxtLamaPinjam;
    private javax.swing.JTextField TxtNamaAnggota;
    private javax.swing.JComboBox TxtNoAnggota;
    private javax.swing.JTextField TxtTanggal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pencarian;
    // End of variables declaration//GEN-END:variables

    private Date getTanggalFromTable(JTable Tabel3, int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
