/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmRepSimpanAnggota.java
 *
 * Created on 26 Jun 12, 13:05:57
 */
package Forms;
import Class.ClassDatabase;
import java.io.File;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class FrmRepPinjamAnggota extends javax.swing.JInternalFrame {

    /** Creates new form FrmRepSimpanAnggota */
    public FrmRepPinjamAnggota() {
        initComponents();
        loadcombodata();
    }
private void loadcombodata(){
    try {        
        TxtNoAnggota.removeAllItems();
        
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select NoAnggota from anggota group by NoAnggota";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                TxtNoAnggota.addItem(r.getString("NoAnggota"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        }   
}

private void loadcombodata2(){
    try {        
        TxtNoPinjam.removeAllItems();
        String kd=(String) this.TxtNoAnggota.getSelectedItem();
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select NoPinjam from pinjaman where NoAnggota='" + kd + "'";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                TxtNoPinjam.addItem(r.getString("NoPinjam"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        }   
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtNoAnggota = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        TxtNamaAnggota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TxtNoPinjam = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        TxtTotalPinjaman = new javax.swing.JTextField();
        TxtAlamat = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);

        jLabel1.setText("Kode Anggota");
        jLabel1.setName("jLabel1"); // NOI18N

        TxtNoAnggota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TxtNoAnggota.setName("TxtNoAnggota"); // NOI18N
        TxtNoAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNoAnggotaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Anggota");
        jLabel2.setName("jLabel2"); // NOI18N

        TxtNamaAnggota.setName("TxtNamaAnggota"); // NOI18N
        TxtNamaAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaAnggotaActionPerformed(evt);
            }
        });

        jLabel3.setText("Alamat");
        jLabel3.setName("jLabel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jButton1.setText("SHOW");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EXIT");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("No Pinjam");
        jLabel4.setName("jLabel4"); // NOI18N

        TxtNoPinjam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TxtNoPinjam.setName("TxtNoPinjam"); // NOI18N
        TxtNoPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNoPinjamActionPerformed(evt);
            }
        });

        jLabel5.setText("Total Pinjaman");
        jLabel5.setName("jLabel5"); // NOI18N

        TxtTotalPinjaman.setName("TxtTotalPinjaman"); // NOI18N
        TxtTotalPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalPinjamanActionPerformed(evt);
            }
        });

        TxtAlamat.setName("TxtAlamat"); // NOI18N
        TxtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAlamatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtNoPinjam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtNoAnggota, 0, 125, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtTotalPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(TxtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(TxtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(TxtNoPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(TxtTotalPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void TxtNamaAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaAnggotaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TxtNamaAnggotaActionPerformed

private void TxtNoAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNoAnggotaActionPerformed
// TODO add your handling code here:
    int i=TxtNoAnggota.getSelectedIndex();
        if (i==-1)
        {
            return;
        }
         try {
             String kd=(String) TxtNoAnggota.getSelectedItem();
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql = "Select * from anggota WHERE NoAnggota=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kd);
            ResultSet result=p.executeQuery();
            result.next();            
            
            this.TxtNamaAnggota.setText(result.getString(2));
            this.TxtAlamat.setText(result.getString("alamat"));
            loadcombodata2();
            }catch(SQLException e){
            System.out.println(e);        
         }
}//GEN-LAST:event_TxtNoAnggotaActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    try {
         
           
           
            
            String reportName = ClassDatabase.PathReport + "RepAngsuranAnggota.jasper";
            HashMap parameter = new HashMap();
            File reportFile = new File(reportName);
            parameter.put("NoAnggota",(String) this.TxtNoAnggota.getSelectedItem());
            parameter.put("NamaAnggota",this.TxtNamaAnggota.getText());
            parameter.put("alamat",this.TxtAlamat.getText());
            parameter.put("nopinjam",(String)this.TxtNoPinjam.getSelectedItem());
            parameter.put("totalpinjam",this.TxtTotalPinjaman.getText());

            JasperReport jReport = (JasperReport)JRLoader.loadObject(reportFile.getPath());
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameter, ClassDatabase.getkoneksi());
            JRViewer viewer = new JRViewer(jPrint);
            viewer.setOpaque(true);
            viewer.setVisible(true);           
           jScrollPane1.add(viewer);
           jScrollPane1.setViewportView(viewer);
           
            } catch (Exception ex) {
                System.out.println(ex);
            }
}//GEN-LAST:event_jButton1ActionPerformed

private void TxtTotalPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalPinjamanActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TxtTotalPinjamanActionPerformed

private void TxtNoPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNoPinjamActionPerformed
// TODO add your handling code here:
    int i=TxtNoPinjam.getSelectedIndex();
        if (i==-1)
        {
            return;
        }
         try {
             String kd=(String) TxtNoPinjam.getSelectedItem();
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql = "Select * from pinjaman WHERE NoPinjam=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kd);
            ResultSet result=p.executeQuery();
            result.next();            
            
            this.TxtTotalPinjaman.setText(result.getString("jumlah"));
           
            loadcombodata2();
            }catch(SQLException e){
            System.out.println(e);        
         }
}//GEN-LAST:event_TxtNoPinjamActionPerformed

private void TxtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAlamatActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TxtAlamatActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtAlamat;
    private javax.swing.JTextField TxtNamaAnggota;
    private javax.swing.JComboBox TxtNoAnggota;
    private javax.swing.JComboBox TxtNoPinjam;
    private javax.swing.JTextField TxtTotalPinjaman;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
