/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmRepSimpanAnggota.java
 *
 * Created on 26 Jun 12, 13:05:57
 */
package Forms;
import Class.ClassDatabase;
import java.io.File;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class FrmRepSimpanAnggota extends javax.swing.JInternalFrame {

    /** Creates new form FrmRepSimpanAnggota */
    public FrmRepSimpanAnggota() {
        initComponents();
        loadcombodata();
    }
private void loadcombodata(){
    try {        
        TxtNoAnggota.removeAllItems();
        
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select NoAnggota from anggota group by NoAnggota";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                TxtNoAnggota.addItem(r.getString("NoAnggota"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        }   
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtNoAnggota = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        TxtNamaAnggota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtTgl = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        jLabel1.setText("Kode Anggota");
        jLabel1.setName("jLabel1"); // NOI18N

        TxtNoAnggota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TxtNoAnggota.setName("TxtNoAnggota"); // NOI18N
        TxtNoAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNoAnggotaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Anggota");
        jLabel2.setName("jLabel2"); // NOI18N

        TxtNamaAnggota.setName("TxtNamaAnggota"); // NOI18N
        TxtNamaAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaAnggotaActionPerformed(evt);
            }
        });

        jLabel3.setText("Tanggal Masuk");
        jLabel3.setName("jLabel3"); // NOI18N

        TxtTgl.setName("TxtTgl"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jButton1.setText("SHOW");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EXIT");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TxtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(TxtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addComponent(TxtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void TxtNamaAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaAnggotaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TxtNamaAnggotaActionPerformed

private void TxtNoAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNoAnggotaActionPerformed
// TODO add your handling code here:
    int i=TxtNoAnggota.getSelectedIndex();
        if (i==-1)
        {
            return;
        }
         try {
             String kd=(String) TxtNoAnggota.getSelectedItem();
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql = "Select * from anggota WHERE NoAnggota=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kd);
            ResultSet result=p.executeQuery();
            result.next();            
            
            this.TxtNamaAnggota.setText(result.getString(2));
            this.TxtTgl.setDate(result.getDate("Tgl_Masuk"));
            
            }catch(SQLException e){
            System.out.println(e);        
         }
}//GEN-LAST:event_TxtNoAnggotaActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    try {
         
           
           
            
            String reportName = ClassDatabase.PathReport + "FrmRepSimpanAnggota.jasper";
            HashMap parameter = new HashMap();
            File reportFile = new File(reportName);
            parameter.put("NoAnggota",(String) this.TxtNoAnggota.getSelectedItem());
            parameter.put("NamaAnggota",this.TxtNamaAnggota.getText());
            parameter.put("TanggalMasuk",this.TxtTgl.getDate());

            JasperReport jReport = (JasperReport)JRLoader.loadObject(reportFile.getPath());
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameter, ClassDatabase.getkoneksi());
            JRViewer viewer = new JRViewer(jPrint);
            viewer.setOpaque(true);
            viewer.setVisible(true);           
           jScrollPane1.add(viewer);
           jScrollPane1.setViewportView(viewer);
           
            } catch (Exception ex) {
                System.out.println(ex);
            }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtNamaAnggota;
    private javax.swing.JComboBox TxtNoAnggota;
    private com.toedter.calendar.JDateChooser TxtTgl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
