/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmSimpanan.java
 *
 * Created on 25 Jun 12, 22:49:17
 */
package Forms;
import Class.ClassDatabase;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class FrmSimpanan extends javax.swing.JInternalFrame {

    /** Creates new form FrmSimpanan */
    public FrmSimpanan() {
        initComponents();
        loadcombodata();
        datatabel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tambah = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtNamaAnggota = new javax.swing.JTextField();
        Hapus = new javax.swing.JButton();
        TxtWajib = new javax.swing.JTextField();
        Cari = new javax.swing.JButton();
        TxtTgl = new com.toedter.calendar.JDateChooser();
        TxtNoAnggota = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        TxtKodeTransaksi = new javax.swing.JTextField();
        TxtSukarela = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtPokok = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel2 = new javax.swing.JTable();
        pencarian = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 102));

        Tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/reset.png"))); // NOI18N
        Tambah.setText("Tambah");
        Tambah.setName("Tambah"); // NOI18N
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/edit.png"))); // NOI18N
        Edit.setText("Edit");
        Edit.setName("Edit"); // NOI18N
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/add.png"))); // NOI18N
        Simpan.setText("Simpan");
        Simpan.setName("Simpan"); // NOI18N
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nama Anggota");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Simp. Wajib");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nomor Anggota");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tanggal Simpan");
        jLabel1.setName("jLabel1"); // NOI18N

        TxtNamaAnggota.setName("TxtNamaAnggota"); // NOI18N
        TxtNamaAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaAnggotaActionPerformed(evt);
            }
        });

        Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/hapus.png"))); // NOI18N
        Hapus.setText("Hapus");
        Hapus.setName("Hapus"); // NOI18N
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        TxtWajib.setName("TxtWajib"); // NOI18N

        Cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/sign-out-option.png"))); // NOI18N
        Cari.setText("Tutup");
        Cari.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cari.setName("Cari"); // NOI18N
        Cari.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Cari.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });

        TxtTgl.setName("TxtTgl"); // NOI18N

        TxtNoAnggota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TxtNoAnggota.setName("TxtNoAnggota"); // NOI18N
        TxtNoAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNoAnggotaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Kode Transaksi");
        jLabel6.setName("jLabel6"); // NOI18N

        TxtKodeTransaksi.setName("TxtKodeTransaksi"); // NOI18N
        TxtKodeTransaksi.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtKodeTransaksiCaretUpdate(evt);
            }
        });
        TxtKodeTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKodeTransaksiActionPerformed(evt);
            }
        });

        TxtSukarela.setName("TxtSukarela"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Simp. Sukarela");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Simp. Pokok");
        jLabel8.setName("jLabel8"); // NOI18N

        TxtPokok.setName("TxtPokok"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Total");
        jLabel9.setName("jLabel9"); // NOI18N

        TxtTotal.setName("TxtTotal"); // NOI18N
        TxtTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtTotalMouseClicked(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        Tabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel2.setName("Tabel2"); // NOI18N
        Tabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tabel2MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel2);

        pencarian.setName("pencarian"); // NOI18N
        pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/search.png"))); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("INPUT DATA SIMPANAN");
        jLabel5.setName("jLabel5"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(Tambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Simpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hapus)
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtKodeTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(TxtSukarela, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22)
                        .addComponent(TxtWajib, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(TxtPokok, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cari, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pencarian)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(TxtKodeTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(TxtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtWajib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TxtSukarela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TxtPokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //untuk tampilkan tulisan title tabel
         public void datatabel(){
        DefaultTableModel tab=new DefaultTableModel();
        tab.addColumn("No Transaksi");
        tab.addColumn("Tanggal Transaksi");
        tab.addColumn("No Anggota");
        tab.addColumn("Simpanan Wajib");
        tab.addColumn("Simpanan Sekarela");
        tab.addColumn("Total Simpanan");
        
        
            Tabel2.setModel(tab);
            try{
                Statement statement=(Statement) ClassDatabase.getkoneksi().createStatement();
                ResultSet rs=statement.executeQuery("select * from simpanan Order by NoTrans");
                while(rs.next())
                {
                    tab.addRow(new Object[]{
                        rs.getString("NoTrans"),
                        rs.getString("TglTrans"),
                        rs.getString("NoAnggota"),
                        rs.getString("Wajib"),
                        rs.getString("Sukarela"),
                        rs.getString("TotalSimpanan")});
                        
                }
                Tabel2.setModel(tab);
                } catch (SQLException e){
            }
    }
private void TxtNamaAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaAnggotaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TxtNamaAnggotaActionPerformed

private void TxtKodeTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKodeTransaksiActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TxtKodeTransaksiActionPerformed

private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
// TODO add your handling code here:
    try {        
        
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select NoTrans from Simpanan order by NoTrans desc";
            ResultSet r=s.executeQuery(sql);
            
            if(r.next())
            {
                StringBuffer strBuf = new StringBuffer();
                strBuf.append(r.getString("NoTrans"));
                String kd=String.valueOf(strBuf.delete(0, 2));
                int no_t=Integer.parseInt(kd) +1;
                
               
                this.TxtKodeTransaksi.setText("SP" + String.valueOf(no_t));
            }else{
                int no_t=1;
                this.TxtKodeTransaksi.setText("SP" + String.valueOf(no_t));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        }        
    //untuk tobol reset
        TxtWajib.setText("");
        TxtSukarela.setText("");
        TxtTotal.setText("");
        TxtTgl.setDate(null);
}//GEN-LAST:event_TambahActionPerformed

private void TxtNoAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNoAnggotaActionPerformed
// TODO add your handling code here:
    int i=TxtNoAnggota.getSelectedIndex();
        if (i==-1)
        {
            return;
        }
         try {
             String kd=(String) TxtNoAnggota.getSelectedItem();
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql = "Select * from anggota WHERE NoAnggota=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kd);
            ResultSet result=p.executeQuery();
            result.next();            
            
            this.TxtNamaAnggota.setText(result.getString(2));
            this.TxtPokok.setText(result.getString("SimpananPokok"));
            
            
            }catch(SQLException e){
            System.out.println(e);        
         }
   
}//GEN-LAST:event_TxtNoAnggotaActionPerformed

private void getSimpanan()
{
    try {
        DecimalFormat df = new DecimalFormat("#.##");
             String kd=(String) TxtNoAnggota.getSelectedItem();
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql = "Select sum(wajib) as wj,sum(sukarela)as sk from simpanan WHERE NoAnggota=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kd);
            ResultSet result=p.executeQuery();
            if(result.next())
            {
                Double wj=Double.parseDouble(result.getString("wj"));
                Double sk=Double.parseDouble(result.getString("sk"));
                Double pk=Double.parseDouble(this.TxtPokok.getText());
                Double tt=wj+sk+pk;
                
                this.TxtTotal.setText(String.valueOf(df.format(tt)));
            }
            
            
            
            }catch(SQLException e){
            System.out.println(e);        
         }
}

private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
// TODO add your handling code here:
    java.util.Date tgl=(java.util.Date) this.TxtTgl.getDate();
    String kodeA=(String)this.TxtNoAnggota.getSelectedItem();
    String kodeT=this.TxtKodeTransaksi.getText();
    String wajib=this.TxtWajib.getText();
    String sukarela=this.TxtSukarela.getText();
    String total=this.TxtTotal.getText();
    
    try {
            Connection c=ClassDatabase.getkoneksi();
            String sql = "Insert into simpanan values (?,?,?,?,?,?)";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kodeT);
            p.setDate(2, new java.sql.Date(tgl.getTime()));
            p.setString(3, kodeA);  
            p.setString(4, wajib);
             p.setString(5, sukarela);
             p.setString(6, total);
           
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Tambah data");
        }catch(SQLException e){
            System.out.println(e);
        }finally{
            
            
        }
    datatabel();
}//GEN-LAST:event_SimpanActionPerformed

private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
// TODO add your handling code here:
    java.util.Date tgl=(java.util.Date) this.TxtTgl.getDate();
    String kodeA=(String)this.TxtNoAnggota.getSelectedItem();
    String kodeT=this.TxtKodeTransaksi.getText();
    String wajib=this.TxtWajib.getText();
    String sukarela=this.TxtSukarela.getText();
    String total=this.TxtTotal.getText();
    try {
            Connection c=ClassDatabase.getkoneksi();
            String sql = "Update `koperasi`.`simpanan` SET `TglTrans`=?,`NoAnggota`=?,`Wajib`=?,`Sukarela`=?,`TotalSimpanan`=? Where NoTrans=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setDate(1, new java.sql.Date(tgl.getTime()));
            p.setString(2, kodeA);  
            p.setString(3, wajib);
            p.setString(4, sukarela);
            p.setString(6, kodeT);
            p.setString(5, total);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Update data");
        }catch(SQLException e){
            System.out.println(e);
        }finally{
            
            
        }
    datatabel();
}//GEN-LAST:event_EditActionPerformed

private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
// TODO add your handling code here:
    
    String kodeT=this.TxtKodeTransaksi.getText();
   
    try {
            Connection c=ClassDatabase.getkoneksi();
            String sql = "Delete from simpanan Where NoTrans=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kodeT);
            
           
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Delete data");
        }catch(SQLException e){
            System.out.println(e);
        }finally{
            
            
        }
    datatabel();
}//GEN-LAST:event_HapusActionPerformed

private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_CariActionPerformed

private void TxtKodeTransaksiCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtKodeTransaksiCaretUpdate
// TODO add your handling code here:
    try {            
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select * from simpanan where NoTrans='" + this.TxtKodeTransaksi.getText() + "'";
            ResultSet r=s.executeQuery(sql);
            
           while (r.next()){
               
                this.TxtTgl.setDate(r.getDate("TglTrans"));
                this.TxtNoAnggota.setSelectedItem(r.getString("NoAnggota"));
                this.TxtWajib.setText(r.getString("Wajib"));
                this.TxtSukarela.setText(r.getString("Sukarela"));
                this.TxtTotal.setText(r.getString("TotalSimpanan"));
            }
            r.close();
            s.close();
            
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan" + e);
        }
}//GEN-LAST:event_TxtKodeTransaksiCaretUpdate

    private void Tabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel2MouseClicked
        // TODO add your handling code here:
         // untuk tabel
        TxtKodeTransaksi.setText(Tabel2.getValueAt(Tabel2.getSelectedRow(), 0).toString());
        TxtWajib.setText(Tabel2.getValueAt(Tabel2.getSelectedRow(), 3).toString());
        TxtSukarela.setText(Tabel2.getValueAt(Tabel2.getSelectedRow(), 4).toString());  
        TxtTotal.setText(Tabel2.getValueAt(Tabel2.getSelectedRow(), 5).toString());                         
    }//GEN-LAST:event_Tabel2MouseClicked

    private void Tabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel2MousePressed
        // TODO add your handling code here:
         //untuk menampilkan date jika di klik isi tabel
        if(evt.getClickCount()==1){
            TxtTgl.setDate(getTanggalFromTable(Tabel2, 1));
        }
    }//GEN-LAST:event_Tabel2MousePressed

    private void TxtTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTotalMouseClicked
        // TODO add your handling code here:
         //untuk perhitungan jumlah total simpanan
        if(TxtWajib.getText().isEmpty()&&TxtSukarela.getText().isEmpty()&&TxtPokok.getText().isEmpty()){
            TxtWajib.setText("");
             TxtSukarela.setText("");
             TxtPokok.setText("");
    }

       int wajib = Integer.parseInt(TxtWajib.getText());
       int sukarela= Integer.parseInt(TxtSukarela.getText());
       int pokok= Integer.parseInt(TxtPokok.getText());
       int totalsimpanan = wajib + sukarela + pokok;

       TxtTotal.setText(String.valueOf(totalsimpanan)); 
    }//GEN-LAST:event_TxtTotalMouseClicked

    private void pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianActionPerformed
        // TODO add your handling code here:
         // untuk pencarian
        DefaultTableModel tab= new DefaultTableModel();
        tab.addColumn("No Transaksi");
        tab.addColumn("Tanggal Transaksi");
        tab.addColumn("No Anggota");
        tab.addColumn("Simpanan Wajib");
        tab.addColumn("Simpanan Sekarela");
        tab.addColumn("Total Simpanan");

try{
Statement statement =(Statement)ClassDatabase.getkoneksi().createStatement();
ResultSet rs = statement.executeQuery("select * from simpanan where NoAnggota like '%"+pencarian.getText()+"%'");
   while (rs.next()) {
     tab.addRow(new Object[]{
     rs.getString(1),
     rs.getString(2),
     rs.getString(3),
     rs.getString(4),
     rs.getString(5),
     rs.getString(6)
     
});
}
Tabel2.setModel(tab);

}catch (Exception e){
}
    }//GEN-LAST:event_pencarianActionPerformed
private void loadcombodata(){
    try {        
        TxtNoAnggota.removeAllItems();
        
            Connection c=ClassDatabase.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select NoAnggota from anggota group by NoAnggota";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                TxtNoAnggota.addItem(r.getString("NoAnggota"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        }   
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cari;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Simpan;
    private javax.swing.JTable Tabel2;
    private javax.swing.JButton Tambah;
    private javax.swing.JTextField TxtKodeTransaksi;
    private javax.swing.JTextField TxtNamaAnggota;
    private javax.swing.JComboBox TxtNoAnggota;
    private javax.swing.JTextField TxtPokok;
    private javax.swing.JTextField TxtSukarela;
    private com.toedter.calendar.JDateChooser TxtTgl;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JTextField TxtWajib;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pencarian;
    // End of variables declaration//GEN-END:variables

    private Date getTanggalFromTable(JTable Tabel2, int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
